import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Physical AI & Humanoid Robotics Course Modules
  courseModules: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Course Overview',
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin Simulation',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac Integration',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Pipeline',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4',
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      collapsed: true,
      items: [
        'capstone-guidance',
        'debugging-guide',
        'bibliography',
      ],
    },
  ],
};

export default sidebars;
